# -*- coding: utf-8 -*-
"""brazilian-ecommerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TvuAw2yzfcXXcAQm3eN8gBtt3vDc3ibv

#### Import Data
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load all datasets
customers_dataset = pd.read_csv('/content/drive/MyDrive/brazilian-ecommerce/olist_customers_dataset.csv')
geolocation_dataset = pd.read_csv('/content/drive/MyDrive/brazilian-ecommerce/olist_geolocation_dataset.csv')
order_items_dataset = pd.read_csv('/content/drive/MyDrive/brazilian-ecommerce/olist_order_items_dataset.csv')
order_payments_dataset = pd.read_csv('/content/drive/MyDrive/brazilian-ecommerce/olist_order_payments_dataset.csv')
order_reviews_dataset = pd.read_csv('/content/drive/MyDrive/brazilian-ecommerce/olist_order_reviews_dataset.csv')
orders_dataset = pd.read_csv('/content/drive/MyDrive/brazilian-ecommerce/olist_orders_dataset.csv')
products_dataset = pd.read_csv('/content/drive/MyDrive/brazilian-ecommerce/olist_products_dataset.csv')
sellers_dataset = pd.read_csv('/content/drive/MyDrive/brazilian-ecommerce/olist_sellers_dataset.csv')
product_category = pd.read_csv('/content/drive/MyDrive/brazilian-ecommerce/product_category_name_translation.csv')

"""#### Check for Missing Values"""

print('--- Missing Values in customers_dataset ---')
display(customers_dataset.isnull().sum())

print('\n--- Missing Values in geolocation_dataset ---')
display(geolocation_dataset.isnull().sum())

print('\n--- Missing Values in order_items_dataset ---')
display(order_items_dataset.isnull().sum())

print('\n--- Missing Values in order_payments_dataset ---')
display(order_payments_dataset.isnull().sum())

print('\n--- Missing Values in order_reviews_dataset ---')
display(order_reviews_dataset.isnull().sum())

print('\n--- Missing Values in orders_dataset ---')
display(orders_dataset.isnull().sum())

print('\n--- Missing Values in products_dataset ---')
display(products_dataset.isnull().sum())

print('\n--- Missing Values in sellers_dataset ---')
display(sellers_dataset.isnull().sum())

print('\n--- Missing Values in product_category ---')
display(product_category.isnull().sum())

"""#### Merging Datasets"""

# 1. Pre-process geolocation_dataset
# Group by zip code and take the mean of lat/lng and the first city/state.
print("Processing geolocation_dataset...")
geolocation_processed = geolocation_dataset.groupby('geolocation_zip_code_prefix').agg(
    geolocation_lat=('geolocation_lat', 'mean'),
    geolocation_lng=('geolocation_lng', 'mean'),
    geolocation_city=('geolocation_city', lambda x: x.iloc[0]), # Get the first city
    geolocation_state=('geolocation_state', lambda x: x.iloc[0]) # Get the first state
).reset_index()

# 2. Merge geolocation into customers_dataset
print("Merging geolocation with customers_dataset...")
customers_with_geo = pd.merge(customers_dataset, geolocation_processed,
                              left_on='customer_zip_code_prefix',
                              right_on='geolocation_zip_code_prefix',
                              how='left')
customers_with_geo.drop(columns=['geolocation_zip_code_prefix'], inplace=True)
customers_with_geo.rename(columns={
    'geolocation_lat': 'customer_geolocation_lat',
    'geolocation_lng': 'customer_geolocation_lng',
    'geolocation_city': 'customer_geolocation_city',
    'geolocation_state': 'customer_geolocation_state'
}, inplace=True)

# 3. Merge geolocation into sellers_dataset
print("Merging geolocation with sellers_dataset...")
sellers_with_geo = pd.merge(sellers_dataset, geolocation_processed,
                            left_on='seller_zip_code_prefix',
                            right_on='geolocation_zip_code_prefix',
                            how='left')
sellers_with_geo.drop(columns=['geolocation_zip_code_prefix'], inplace=True)
sellers_with_geo.rename(columns={
    'geolocation_lat': 'seller_geolocation_lat',
    'geolocation_lng': 'seller_geolocation_lng',
    'geolocation_city': 'seller_geolocation_city',
    'geolocation_state': 'seller_geolocation_state'
}, inplace=True)

print("Geolocation data processed and merged with customers and sellers.")

# 4. Start the main DataFrame with orders_dataset
print("Starting main DataFrame with orders_dataset...")
main_df = orders_dataset.copy()

# 5. Merge with customers_with_geo (includes customer geo info)
print("Merging with customers_with_geo...")
main_df = pd.merge(main_df, customers_with_geo, on='customer_id', how='left')

# 6. Merge with order_payments_dataset
print("Merging with order_payments_dataset...")
main_df = pd.merge(main_df, order_payments_dataset, on='order_id', how='left')

# 7. Merge with order_reviews_dataset
print("Merging with order_reviews_dataset...")
main_df = pd.merge(main_df, order_reviews_dataset, on='order_id', how='left')

# 8. Merge with order_items_dataset
print("Merging with order_items_dataset...")
main_df = pd.merge(main_df, order_items_dataset, on='order_id', how='left')

# 9. Merge with products_dataset
print("Merging with products_dataset...")
main_df = pd.merge(main_df, products_dataset, on='product_id', how='left')

# 10. Merge with product_category (product category name translation)
print("Merging with product_category...")
main_df = pd.merge(main_df, product_category, on='product_category_name', how='left')

# 11. Merge with sellers_with_geo (includes seller geo info)
print("Merging with sellers_with_geo...")
main_df = pd.merge(main_df, sellers_with_geo, on='seller_id', how='left')

print("All datasets merged into main_df.")
print("\nShape of the final merged DataFrame:", main_df.shape)
print("\nFirst 5 rows of the merged DataFrame:")
display(main_df.head())

"""#### Identifying Potential Relationships (Common Columns)"""

all_datasets = [
    ('customers_dataset', customers_dataset),
    ('geolocation_dataset', geolocation_dataset),
    ('order_items_dataset', order_items_dataset),
    ('order_payments_dataset', order_payments_dataset),
    ('order_reviews_dataset', order_reviews_dataset),
    ('orders_dataset', orders_dataset),
    ('products_dataset', products_dataset),
    ('sellers_dataset', sellers_dataset),
    ('product_category', product_category)
]

print('--- Common Columns (Potential Join Keys) ---')
for i in range(len(all_datasets)):
    for j in range(i + 1, len(all_datasets)):
        name1, df1 = all_datasets[i]
        name2, df2 = all_datasets[j]

        common_cols = list(set(df1.columns) & set(df2.columns))
        if common_cols:
            print(f'\n{name1} and {name2} share columns: {common_cols}')

"""#### Data Exploration"""

for name, df in all_datasets:
    print(f"\n{'='*50}\nDataset: {name}\n{'='*50}")

    print("\n--- Info ---")
    df.info()

    print("\n--- Descriptive Statistics ---")
    display(df.describe(include='all'))

    print("\n--- Top Unique Values for Object Columns ---")
    for col in df.select_dtypes(include='object').columns:
        print(f"Column '{col}':")
        display(df[col].value_counts(dropna=False).head(10))

    print("\n")

"""#### Handling Missing Values"""

import numpy as np

# List of all dataframes to process
datasets_to_clean = [
    ('customers_dataset', customers_dataset),
    ('geolocation_dataset', geolocation_dataset),
    ('order_items_dataset', order_items_dataset),
    ('order_payments_dataset', order_payments_dataset),
    ('order_reviews_dataset', order_reviews_dataset),
    ('orders_dataset', orders_dataset),
    ('products_dataset', products_dataset),
    ('sellers_dataset', sellers_dataset),
    ('product_category', product_category)
]

for name, df in datasets_to_clean:
    print(f"\n--- Processing Missing Values for {name} ---")

    # Convert date/time columns to datetime type first
    if name == 'orders_dataset':
        for col_date in ['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']:
            if col_date in df.columns:
                df[col_date] = pd.to_datetime(df[col_date], errors='coerce')

    if name == 'order_items_dataset':
        for col_date in ['shipping_limit_date']:
            if col_date in df.columns:
                df[col_date] = pd.to_datetime(df[col_date], errors='coerce')

    if name == 'order_reviews_dataset':
        for col_date in ['review_creation_date', 'review_answer_timestamp']:
            if col_date in df.columns:
                df[col_date] = pd.to_datetime(df[col_date], errors='coerce')

    # Iterate through columns and fill missing values based on data type
    for col in df.columns:
        if df[col].isnull().any(): # Check if there are any missing values in the column
            if pd.api.types.is_numeric_dtype(df[col]):
                median_val = df[col].median()
                df[col].fillna(median_val, inplace=True)
                print(f"  Filled numeric column '{col}' with median: {median_val}")
            elif pd.api.types.is_object_dtype(df[col]):
                # For object type, fill with 'unknown'
                df[col].fillna('unknown', inplace=True)
                print(f"  Filled object column '{col}' with 'unknown'")
            elif pd.api.types.is_datetime64_any_dtype(df[col]):
                # For datetime type, fill with pd.NaT
                df[col].fillna(pd.NaT, inplace=True)
                print(f"  Filled datetime column '{col}' with pd.NaT")

    print(f"  Missing values after filling for {name}:")
    display(df.isnull().sum())

"""#### Summary of the Merged DataFrame (`main_df`)"""

print("\n--- Info of main_df ---")
main_df.info()

print("\n--- Descriptive Statistics of main_df ---")
display(main_df.describe(include='all'))

print("\n--- Missing Values in main_df (Top 20) ---")
missing_values_main_df = main_df.isnull().sum()
missing_values_main_df = missing_values_main_df[missing_values_main_df > 0].sort_values(ascending=False)
display(missing_values_main_df.head(20))

"""#### Handling Missing Values in `main_df`

Based on the previous summary, there are still some missing values after the merging process. We will handle these missing values with the following strategy:

*   Numeric columns will be filled with their median value.
*   Categorical/object columns will be filled with the string 'unknown'.
*   Date/time columns will be filled with `pd.NaT` (Not a Time).
"""

import numpy as np

print("--- Handling Missing Values in main_df ---")

# Iterate through columns of main_df and fill missing values based on data type
for col in main_df.columns:
    if main_df[col].isnull().any(): # Check if there are any missing values in the column
        if pd.api.types.is_numeric_dtype(main_df[col]):
            median_val = main_df[col].median()
            main_df[col] = main_df[col].fillna(median_val)
            print(f"  Filled numeric column '{col}' with median: {median_val}")
        elif pd.api.types.is_object_dtype(main_df[col]):
            # For object type, fill with 'unknown'
            main_df[col] = main_df[col].fillna('unknown')
            print(f"  Filled object column '{col}' with 'unknown'")
        elif pd.api.types.is_datetime64_any_dtype(main_df[col]):
            # For datetime type, fill with pd.NaT
            main_df[col] = main_df[col].fillna(pd.NaT)
            print(f"  Filled datetime column '{col}' with pd.NaT")

print("\n--- Missing values in main_df after filling ---")
display(main_df.isnull().sum()[main_df.isnull().sum() > 0]) # Display only columns with remaining missing values

"""#### Revenue Analysis by Product Category

Now that missing values have been handled, let's analyze the product categories that generate the most revenue. We will group `main_df` by `product_category_name_english` and sum the `payment_value` for each category.
"""

# Calculate total revenue per product category
revenue_by_category = main_df.groupby('product_category_name_english')['payment_value'].sum().sort_values(ascending=False)

print("--- Top 10 Product Categories by Revenue ---")
display(revenue_by_category.head(10))

"""Visualizing the top 10 product categories by revenue will provide a clearer picture."""

import matplotlib.pyplot as plt
import seaborn as sns

# Get the top 10 categories for visualization
top_10_categories = revenue_by_category.head(10)

plt.figure(figsize=(12, 7))
sns.barplot(x=top_10_categories.values, y=top_10_categories.index, palette='viridis')
plt.title('Top 10 Product Categories by Total Revenue')
plt.xlabel('Total Revenue (R$)')
plt.ylabel('Product Category (English)')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""#### Analysis of Cities with the Most Customers

Next, let's identify the cities with the highest number of customers. This can provide insights into the geographical distribution of the customer base.
"""

# Calculate the number of unique customers per city
customers_by_city = main_df.groupby('customer_city')['customer_unique_id'].nunique().sort_values(ascending=False)

print("--- Top 10 Cities by Number of Unique Customers ---")
display(customers_by_city.head(10))

"""Visualizing this data will help in understanding customer distribution more clearly."""

import matplotlib.pyplot as plt
import seaborn as sns

# Get the top 10 cities for visualization
top_10_cities = customers_by_city.head(10)

plt.figure(figsize=(12, 7))
sns.barplot(x=top_10_cities.values, y=top_10_cities.index, palette='crest')
plt.title('Top 10 Cities by Number of Unique Customers')
plt.xlabel('Number of Unique Customers')
plt.ylabel('City')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""#### Analysis of Months with Highest Sales

Next, let's identify the months with the highest sales (`payment_value`) to observe seasonal trends or peak sales periods.
"""

import pandas as pd

# Ensure the column is in datetime format
main_df['order_purchase_timestamp'] = pd.to_datetime(main_df['order_purchase_timestamp'])

# Extract month from order_purchase_timestamp
main_df['order_purchase_month'] = main_df['order_purchase_timestamp'].dt.month

# Calculate total sales per month
sales_by_month = main_df.groupby('order_purchase_month')['payment_value'].sum().sort_values(ascending=False)

print("--- Top Months by Total Sales ---")
display(sales_by_month)

"""For better visualization, we can display the monthly sales data in a graph."""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Ensure 'order_purchase_timestamp' is datetime type
main_df['order_purchase_timestamp'] = pd.to_datetime(main_df['order_purchase_timestamp'])
# Ensure 'order_purchase_month' is created
main_df['order_purchase_month'] = main_df['order_purchase_timestamp'].dt.month

# Sort months chronologically for line visualization
sales_by_month_sorted = main_df.groupby('order_purchase_month')['payment_value'].sum().sort_index()

plt.figure(figsize=(12, 7))
sns.barplot(x=sales_by_month_sorted.index, y=sales_by_month_sorted.values, palette='Blues_d', hue=sales_by_month_sorted.index, legend=False)
plt.title('Total Sales by Month')
plt.xlabel('Month')
plt.ylabel('Total Sales (R$)')
plt.xticks(ticks=range(0, 12), labels=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""#### Average Order Delivery Time

Now, let's calculate the average time it takes for an order to be delivered to the customer. This can provide insights into logistics efficiency.
"""

import numpy as np
import pandas as pd

# Ensure both columns are in datetime format
main_df['order_delivered_customer_date'] = pd.to_datetime(main_df['order_delivered_customer_date'], errors='coerce')
main_df['order_purchase_timestamp'] = pd.to_datetime(main_df['order_purchase_timestamp'], errors='coerce')

# Calculate delivery duration (difference between delivered date and purchase date)
# Use .dt.days to get the duration in days, ignoring NaT values
main_df['delivery_duration'] = (main_df['order_delivered_customer_date'] - main_df['order_purchase_timestamp']).dt.days

# Calculate the average delivery duration, ignoring NaN values that result from pd.NaT
average_delivery_time_days = main_df['delivery_duration'].mean()

print(f"Average order delivery time: {average_delivery_time_days:.2f} days")

"""#### Customer Repeat Order Analysis

To understand customer loyalty, let's identify if there are customers who make purchases more than once (repeat orders).
"""

# Calculate the number of unique orders per customer_unique_id
repeat_customers = main_df.groupby('customer_unique_id')['order_id'].nunique()

# Filter customers with more than one order
repeat_customers = repeat_customers[repeat_customers > 1]

print(f"Number of customers making repeat orders: {len(repeat_customers)}")
print("--- Top 10 Customers by Repeat Orders ---")
display(repeat_customers.sort_values(ascending=False).head(10))

"""#### Further Analysis and Potential Project Ideas

After performing basic analysis, this dataset still holds significant potential for further exploration and predictive model development. Here are some ideas you can expand upon:

1.  **Customer Segmentation**:
    *   **RFM Analysis (Recency, Frequency, Monetary)**: Group customers based on their last purchase (Recency), how often they buy (Frequency), and how much money they spend (Monetary). This can aid in targeted marketing strategies.
    *   **Behavioral Segmentation**: Identify customer groups based on the product categories they purchase, average order value, or other purchasing patterns.

2.  **Seller Performance Analysis**:
    *   **Seller Ranking**: Create a seller ranking system based on sales volume, revenue, review scores, and delivery speed.
    *   **Seller vs. Customer Geolocation**: Analyze the distance between sellers and customers to observe its impact on delivery time and customer satisfaction.

3.  **Advanced Product Analysis**:
    *   **Most Profitable Products**: Beyond total revenue, identify products with the highest profit margins (if cost data is available) or those purchased most frequently.
    *   **Complementary Products/Recommendations**: Find products often bought together to build a recommendation system.
    *   **Product Review Analysis**: Perform sentiment analysis on the `review_comment_message` column to gain deeper insights into customer feedback about products.

4.  **Delivery Time and Logistics Analysis**:
    *   **Factors Influencing Delivery Time**: Identify variables that most affect `delivery_duration` (e.g., distance, seller/buyer location, product category, shipping method).
    *   **Route Optimization**: If more detailed route data is available, it can be used for logistics optimization.

5.  **Predictive Models**:
    *   **Sales Prediction**: Build models to forecast future sales based on historical trends and other factors.
    *   **Order Cancellation Prediction**: Identify factors that lead to order cancellations.
    *   **Review Score Prediction**: Predict review scores based on product, seller, and delivery attributes.

6.  **Richer Data Visualizations**:
    *   **Heatmaps**: Visualize the geographical distribution of sales, customers, or sellers using latitude and longitude.
    *   **Interactive Charts**: Use libraries like Plotly or Bokeh to create visualizations that allow users to explore data in more depth.

Let's start with **RFM analysis** for customer segmentation.
"""

# --- ADVANCED ANALYSIS: RFM SEGMENTATION ---
import datetime as dt

# 1. Define a snapshot date (e.g., one day after the last order in the dataset)
snapshot_date = main_df['order_purchase_timestamp'].max() + dt.timedelta(days=1)

# 2. Calculate Recency, Frequency, and Monetary values
rfm = main_df.groupby('customer_unique_id').agg({
    'order_purchase_timestamp': lambda x: (snapshot_date - x.max()).days, # Recency (days since last purchase)
    'order_id': 'nunique',                                               # Frequency (number of unique orders)
    'payment_value': 'sum'                                                # Monetary (total spend)
})

# 3. Rename columns for clarity
rfm.rename(columns={
    'order_purchase_timestamp': 'Recency',
    'order_id': 'Frequency',
    'payment_value': 'Monetary'
}, inplace=True)

# 4. Create scores (1-5) using quantiles
rfm['R_Score'] = pd.qcut(rfm['Recency'], 5, labels=[5, 4, 3, 2, 1]) # Higher score for lower recency
# Note: Since most customers have Frequency = 1 (based on repeat order analysis),
# we might need custom bins or focus more on R and M for Frequency scoring.
# For now, let's create a simplified Frequency score.
# A simple approach for Frequency can be based on actual counts or custom bins.
# For this example, let's adjust frequency scoring slightly if many are 1.
# If most are 1, qcut might give same scores to many. Let's use rank for Frequency if needed or custom bins.
# For now, let's proceed with simple qcut, but be aware of its limitations for skewed data.
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 5, labels=[1, 2, 3, 4, 5]) # Higher score for higher frequency
rfm['M_Score'] = pd.qcut(rfm['Monetary'], 5, labels=[1, 2, 3, 4, 5]) # Higher score for higher monetary value

# Convert scores to int type
rfm['R_Score'] = rfm['R_Score'].astype(int)
rfm['F_Score'] = rfm['F_Score'].astype(int)
rfm['M_Score'] = rfm['M_Score'].astype(int)

# Combine scores to create an RFM segment string
rfm['RFM_Segment'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str) + rfm['M_Score'].astype(str)

# 5. Example of simplified segmentation based on Recency, Frequency, and Monetary scores
def segment_customer(df):
    if df['R_Score'] >= 4 and df['F_Score'] >= 4 and df['M_Score'] >= 4:
        return 'Champions (Loyal, Frequent & Big Spenders)'
    elif df['R_Score'] >= 4 and df['F_Score'] >= 4 and df['M_Score'] < 4:
        return 'Loyal Customers (Frequent & Recent)'
    elif df['R_Score'] <= 2 and df['M_Score'] >= 4:
        return 'At Risk (Big Spenders, but haven\'t purchased lately)'
    elif df['R_Score'] >= 4 and df['M_Score'] <= 2:
        return 'New Customers'
    elif df['F_Score'] >= 4 and df['M_Score'] >= 4:
        return 'Big Spenders (Frequent & High Value)'
    else:
        return 'General / Other'

rfm['Segment'] = rfm.apply(segment_customer, axis=1)

print("--- RFM Customer Segmentation Counts ---")
print(rfm['Segment'].value_counts())

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
# Menghitung jumlah pelanggan di setiap segmen
segment_counts = rfm['Segment'].value_counts()
sns.barplot(x=segment_counts.values, y=segment_counts.index, palette='magma')
plt.title('Customer Segmentation Breakdown (RFM)')
plt.xlabel('Number of Customers')
plt.ylabel('Segment')

# Simpan grafik
plt.savefig('rfm_segments.png', dpi=300, bbox_inches='tight')
plt.show()